create table "public"."embeddings" (
    "id" bigint generated by default as identity not null,
    "embedding" vector,
    "topics" text[],
    "raw_text" text,
    "verbose_version" text,
    "summary" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."records" drop column "embeddings";

alter table "public"."records" add column "processed" boolean not null default false;

CREATE UNIQUE INDEX embeddings_pkey ON public.embeddings USING btree (id);

alter table "public"."embeddings" add constraint "embeddings_pkey" PRIMARY KEY using index "embeddings_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.match_records_embeddings_similarity(query_embedding vector, match_threshold double precision, match_count integer)
 RETURNS TABLE(id integer, raw_text text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
  select
    embeddings.id,
    embeddings.raw_text,
    1 - (embeddings.embedding <=> query_embedding) as similarity
  from embeddings
  where (1 - (embeddings.embedding <=> query_embedding) > match_threshold)
  order by similarity desc
  limit match_count;
$function$
;

grant delete on table "public"."embeddings" to "anon";

grant insert on table "public"."embeddings" to "anon";

grant references on table "public"."embeddings" to "anon";

grant select on table "public"."embeddings" to "anon";

grant trigger on table "public"."embeddings" to "anon";

grant truncate on table "public"."embeddings" to "anon";

grant update on table "public"."embeddings" to "anon";

grant delete on table "public"."embeddings" to "authenticated";

grant insert on table "public"."embeddings" to "authenticated";

grant references on table "public"."embeddings" to "authenticated";

grant select on table "public"."embeddings" to "authenticated";

grant trigger on table "public"."embeddings" to "authenticated";

grant truncate on table "public"."embeddings" to "authenticated";

grant update on table "public"."embeddings" to "authenticated";

grant delete on table "public"."embeddings" to "service_role";

grant insert on table "public"."embeddings" to "service_role";

grant references on table "public"."embeddings" to "service_role";

grant select on table "public"."embeddings" to "service_role";

grant trigger on table "public"."embeddings" to "service_role";

grant truncate on table "public"."embeddings" to "service_role";

grant update on table "public"."embeddings" to "service_role";


